USE [master]
GO

/****** Object:  Database [Lv-402.DB.FoodServe]    Script Date: 4/22/2019 11:20:41 AM ******/
CREATE DATABASE [Lv-402.DB.FoodServe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Lv-402.DB.FoodServe', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TC\MSSQL\DATA\Lv-402.DB.FoodServe.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Lv-402.DB.FoodServe_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.TC\MSSQL\DATA\Lv-402.DB.FoodServe_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Lv-402.DB.FoodServe].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ARITHABORT OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET RECOVERY FULL 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET  MULTI_USER 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Lv-402.DB.FoodServe] SET  READ_WRITE 
GO

